# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/SIMGate.API"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/SIMGate.Domain"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/SIMGate.Infrastructure"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/SIMGate.Frontend"
    schedule:
      interval: "weekly"
